[features]
seeds = false
skip-lint = false
[programs.localnet]
remi = "CNPEe47uccxYFBZ86rvxNsEioZrga5hf3Z9sXdSFebRJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/archuser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
