[features]
seeds = false
skip-lint = false
[programs.localnet]
remi = "CNPEe47uccxYFBZ86rvxNsEioZrga5hf3Z9sXdSFebRJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

init = "yarn run ts-node --project ./tsconfig.json ./scripts/init.ts"
add = "yarn run ts-node --project ./tsconfig.json ./scripts/addLiquid.ts"
swap = "yarn run ts-node --project ./tsconfig.json ./scripts/swap.ts"
balance = "yarn run ts-node --project ./tsconfig.json ./scripts/balance.ts"
